const ErrorCode = {
  valueArray: ["APP_ERROR", "BAD_REQUEST", "FORBIDDEN", "NOT_FOUND", "UNAUTHORIZED", "AREA_NOT_FOUND", "EMAIL_EXIST", "INVALID_OPERATION", "LOGIN_EXIST", "ORDER_FEEDBACK_EXIST", "ORDER_FEEDBACK_NOT_FOUND", "ORDER_NOT_FOUND", "PHONE_EXIST", "SEAT_NOT_FOUND", "STORE_NOT_FOUND", "STORE_USER_EXIST", "USER_NOT_FOUND", "USER_NOT_ACTIVATED", "STORE_USER_NOT_FOUND", "RESET_KEY_NOT_FOUND_OR_EXPIRED", "CATEGORY_NAME_EXIST", "CATEGORY_NOT_FOUND", "PRODUCT_CODE_EXIST", "PRODUCT_NOT_FOUND", "CATEGORY_NAME_ENG_EXIST", "STORE_PRODUCT_NOT_FOUND", "VOUCHER_NOT_FOUND", "VOUCHER_CODE_NOT_FOUND", "INCORRECT_CURRENT_PASSWORD", "AREA_DISABLED", "SEAT_LOCKED", "SEAT_NON_EMPTY", "STORE_PAY_REQUEST_EXIST", "PAY_AMOUNT_NOT_ENOUGH", "ORDER_AND_SEAT_NOT_MATCH", "LIST_ORDER_PRODUCT_EMPTY", "ORDER_PURCHASED", "ORDER_CANCELLED", "STORE_PRODUCT_STOP_TRADING", "STORE_PRODUCT_UNAVAILABLE", "USER_NOT_IN_STORE", "STORE_CLOSED_OR_DEACTIVATED", "VOUCHER_DISABLED", "VOUCHER_CODE_DISABLED", "VOUCHER_CODE_MAX_USED", "VOUCHER_EXPIRED", "VOUCHER_UNUSABLE", "VOUCHER_CODE_AND_PHONE_NOT_MATCH", "VOUCHER_CODE_INVALID", "PRODUCT_STOP_TRADING", "ORDER_PRODUCT_NOT_FOUND", "ORDER_PRODUCT_NOT_MATCH_ORDER", "ORDER_PRODUCT_CANCEL_REASON_REQUIRED", "INVALID_ORDER_STATUS", "SEAT_NOT_IN_SAME_STORE", "NOTIFICATION_NOT_IN_STORE", "STORE_NOTIFICATION_NOT_FOUND", "USER_PROFILE_NOT_FOUND", "SALE_NOT_FOUND", "INVALID_SALE_TIME_CONDITION", "SALE_DISABLED", "SALE_NOT_STARTED", "SALE_ENDED", "STORE_SALE_NOT_FOUND", "STORE_SALE_DISABLED", "FILE_NOT_FOUND", "TOPIC_SUBSCRIPTION_DENIED"],
  labelArray: ["Lỗi máy chủ", "Yêu cầu không hợp lệ", "Yêu cầu bị chặn", "Không tìm thấy", "Chưa được xác thực", "Không tìm thấy khu vực", "Email đã tồn tại", "Thao tác không hợp lệ", "Tên đăng nhập đã tồn tại", "Phản hồi đã tồn tại", "Không tìm thấy phản hồi cho đơn hàng", "Không tìm thấy đơn hàng", "Số điện thoại đã tồn tại", "Không tìm thấy chỗ ngồi", "Không tìm thấy cửa hàng", "Nhân viên đã tồn tại", "Không tìm thấy người dùng", "Người dùng chưa được kích hoạt", "Không tìm thấy nhân viên", "Mã khôi phục đã hết hạn hoặc không tìm thấy", "Tên danh mục đã tồn tại", "Không tìm thấy danh mục", "Mã sản phẩm đã tồn tại", "Không tìm thấy sản phẩm", "Tên danh mục tiếng anh đã tồn tại", "Không tìm thấy sản phẩm của cửa hàng", "Không tìm thấy voucher", "Không tìm thấy mã voucher", "Mật khẩu hiện tại không đúng", "Khu vực đã bị khóa", "Chỗ ngồi đã bị khóa", "Chỗ ngồi đã được sử dụng", "Yêu cầu thanh toán đã tồn tại", "Tiền thanh toán không đủ", "Đơn hàng không khớp vị trí", "Danh sách sản phẩm trống", "Đơn đã được thanh toán", "Đơn đã bị hủy", "Sản phẩm đã ngừng kinh doanh", "Sản phẩm đã hết hàng", "Người dùng không thuộc cửa hàng", "Cửa hàng đã đóng cửa hoặc bị vô hiệu hóa", "Voucher đã bị vô hiệu hóa", "Mã voucher đã bị vô hiệu hóa", "Mã voucher đã hết lượt sử dụng", "Voucher đã hết hạn", "Voucher không khả dụng", "Mã voucher không đúng với số điện thoại", "Mã voucher không hợp lệ", "Sản phẩm đã ngừng kinh doanh", "Không tìm thấy sản phẩm đã đặt", "Sản phẩm đã đặt không khớp đơn hàng", "Lí do hủy sản phẩm không được bỏ trống", "Trạng thái đơn hàng không hợp lệ", "Chỗ ngồi không cùng cửa hàng", "Thông báo không thuộc cửa hàng này", "Không tìm thấy thông báo của cửa hàng", "Không tìm thấy thông tin người dùng", "Không tìm thấy khuyến mãi", "Thời gian khuyến mãi không hợp lệ", "Khuyến mãi đã bị vô hiệu hóa", "Chưa tới thời gian bắt đầu của khuyến mãi", "Khuyến mãi đã kết thúc", "Không tìm thấy khuyến mãi của cửa hàng", "Khuyến mãi của cửa hàng đã bị vô hiệu hóa", "Không tìm thấy file", "Không có quyền đăng ký chủ đề"],
  value: {
    APP_ERROR: "APP_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    AREA_NOT_FOUND: "AREA_NOT_FOUND",
    EMAIL_EXIST: "EMAIL_EXIST",
    INVALID_OPERATION: "INVALID_OPERATION",
    LOGIN_EXIST: "LOGIN_EXIST",
    ORDER_FEEDBACK_EXIST: "ORDER_FEEDBACK_EXIST",
    ORDER_FEEDBACK_NOT_FOUND: "ORDER_FEEDBACK_NOT_FOUND",
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    PHONE_EXIST: "PHONE_EXIST",
    SEAT_NOT_FOUND: "SEAT_NOT_FOUND",
    STORE_NOT_FOUND: "STORE_NOT_FOUND",
    STORE_USER_EXIST: "STORE_USER_EXIST",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_NOT_ACTIVATED: "USER_NOT_ACTIVATED",
    STORE_USER_NOT_FOUND: "STORE_USER_NOT_FOUND",
    RESET_KEY_NOT_FOUND_OR_EXPIRED: "RESET_KEY_NOT_FOUND_OR_EXPIRED",
    CATEGORY_NAME_EXIST: "CATEGORY_NAME_EXIST",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    PRODUCT_CODE_EXIST: "PRODUCT_CODE_EXIST",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    CATEGORY_NAME_ENG_EXIST: "CATEGORY_NAME_ENG_EXIST",
    STORE_PRODUCT_NOT_FOUND: "STORE_PRODUCT_NOT_FOUND",
    VOUCHER_NOT_FOUND: "VOUCHER_NOT_FOUND",
    VOUCHER_CODE_NOT_FOUND: "VOUCHER_CODE_NOT_FOUND",
    INCORRECT_CURRENT_PASSWORD: "INCORRECT_CURRENT_PASSWORD",
    AREA_DISABLED: "AREA_DISABLED",
    SEAT_LOCKED: "SEAT_LOCKED",
    SEAT_NON_EMPTY: "SEAT_NON_EMPTY",
    STORE_PAY_REQUEST_EXIST: "STORE_PAY_REQUEST_EXIST",
    PAY_AMOUNT_NOT_ENOUGH: "PAY_AMOUNT_NOT_ENOUGH",
    ORDER_AND_SEAT_NOT_MATCH: "ORDER_AND_SEAT_NOT_MATCH",
    LIST_ORDER_PRODUCT_EMPTY: "LIST_ORDER_PRODUCT_EMPTY",
    ORDER_PURCHASED: "ORDER_PURCHASED",
    ORDER_CANCELLED: "ORDER_CANCELLED",
    STORE_PRODUCT_STOP_TRADING: "STORE_PRODUCT_STOP_TRADING",
    STORE_PRODUCT_UNAVAILABLE: "STORE_PRODUCT_UNAVAILABLE",
    USER_NOT_IN_STORE: "USER_NOT_IN_STORE",
    STORE_CLOSED_OR_DEACTIVATED: "STORE_CLOSED_OR_DEACTIVATED",
    VOUCHER_DISABLED: "VOUCHER_DISABLED",
    VOUCHER_CODE_DISABLED: "VOUCHER_CODE_DISABLED",
    VOUCHER_CODE_MAX_USED: "VOUCHER_CODE_MAX_USED",
    VOUCHER_EXPIRED: "VOUCHER_EXPIRED",
    VOUCHER_UNUSABLE: "VOUCHER_UNUSABLE",
    VOUCHER_CODE_AND_PHONE_NOT_MATCH: "VOUCHER_CODE_AND_PHONE_NOT_MATCH",
    VOUCHER_CODE_INVALID: "VOUCHER_CODE_INVALID",
    PRODUCT_STOP_TRADING: "PRODUCT_STOP_TRADING",
    ORDER_PRODUCT_NOT_FOUND: "ORDER_PRODUCT_NOT_FOUND",
    ORDER_PRODUCT_NOT_MATCH_ORDER: "ORDER_PRODUCT_NOT_MATCH_ORDER",
    ORDER_PRODUCT_CANCEL_REASON_REQUIRED: "ORDER_PRODUCT_CANCEL_REASON_REQUIRED",
    INVALID_ORDER_STATUS: "INVALID_ORDER_STATUS",
    SEAT_NOT_IN_SAME_STORE: "SEAT_NOT_IN_SAME_STORE",
    NOTIFICATION_NOT_IN_STORE: "NOTIFICATION_NOT_IN_STORE",
    STORE_NOTIFICATION_NOT_FOUND: "STORE_NOTIFICATION_NOT_FOUND",
    USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
    SALE_NOT_FOUND: "SALE_NOT_FOUND",
    INVALID_SALE_TIME_CONDITION: "INVALID_SALE_TIME_CONDITION",
    SALE_DISABLED: "SALE_DISABLED",
    SALE_NOT_STARTED: "SALE_NOT_STARTED",
    SALE_ENDED: "SALE_ENDED",
    STORE_SALE_NOT_FOUND: "STORE_SALE_NOT_FOUND",
    STORE_SALE_DISABLED: "STORE_SALE_DISABLED",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    TOPIC_SUBSCRIPTION_DENIED: "TOPIC_SUBSCRIPTION_DENIED"
  },
  label: {
    APP_ERROR: "Lỗi máy chủ",
    BAD_REQUEST: "Yêu cầu không hợp lệ",
    FORBIDDEN: "Yêu cầu bị chặn",
    NOT_FOUND: "Không tìm thấy",
    UNAUTHORIZED: "Chưa được xác thực",
    AREA_NOT_FOUND: "Không tìm thấy khu vực",
    EMAIL_EXIST: "Email đã tồn tại",
    INVALID_OPERATION: "Thao tác không hợp lệ",
    LOGIN_EXIST: "Tên đăng nhập đã tồn tại",
    ORDER_FEEDBACK_EXIST: "Phản hồi đã tồn tại",
    ORDER_FEEDBACK_NOT_FOUND: "Không tìm thấy phản hồi cho đơn hàng",
    ORDER_NOT_FOUND: "Không tìm thấy đơn hàng",
    PHONE_EXIST: "Số điện thoại đã tồn tại",
    SEAT_NOT_FOUND: "Không tìm thấy chỗ ngồi",
    STORE_NOT_FOUND: "Không tìm thấy cửa hàng",
    STORE_USER_EXIST: "Nhân viên đã tồn tại",
    USER_NOT_FOUND: "Không tìm thấy người dùng",
    USER_NOT_ACTIVATED: "Người dùng chưa được kích hoạt",
    STORE_USER_NOT_FOUND: "Không tìm thấy nhân viên",
    RESET_KEY_NOT_FOUND_OR_EXPIRED: "Mã khôi phục đã hết hạn hoặc không tìm thấy",
    CATEGORY_NAME_EXIST: "Tên danh mục đã tồn tại",
    CATEGORY_NOT_FOUND: "Không tìm thấy danh mục",
    PRODUCT_CODE_EXIST: "Mã sản phẩm đã tồn tại",
    PRODUCT_NOT_FOUND: "Không tìm thấy sản phẩm",
    CATEGORY_NAME_ENG_EXIST: "Tên danh mục tiếng anh đã tồn tại",
    STORE_PRODUCT_NOT_FOUND: "Không tìm thấy sản phẩm của cửa hàng",
    VOUCHER_NOT_FOUND: "Không tìm thấy voucher",
    VOUCHER_CODE_NOT_FOUND: "Không tìm thấy mã voucher",
    INCORRECT_CURRENT_PASSWORD: "Mật khẩu hiện tại không đúng",
    AREA_DISABLED: "Khu vực đã bị khóa",
    SEAT_LOCKED: "Chỗ ngồi đã bị khóa",
    SEAT_NON_EMPTY: "Chỗ ngồi đã được sử dụng",
    STORE_PAY_REQUEST_EXIST: "Yêu cầu thanh toán đã tồn tại",
    PAY_AMOUNT_NOT_ENOUGH: "Tiền thanh toán không đủ",
    ORDER_AND_SEAT_NOT_MATCH: "Đơn hàng không khớp vị trí",
    LIST_ORDER_PRODUCT_EMPTY: "Danh sách sản phẩm trống",
    ORDER_PURCHASED: "Đơn đã được thanh toán",
    ORDER_CANCELLED: "Đơn đã bị hủy",
    STORE_PRODUCT_STOP_TRADING: "Sản phẩm đã ngừng kinh doanh",
    STORE_PRODUCT_UNAVAILABLE: "Sản phẩm đã hết hàng",
    USER_NOT_IN_STORE: "Người dùng không thuộc cửa hàng",
    STORE_CLOSED_OR_DEACTIVATED: "Cửa hàng đã đóng cửa hoặc bị vô hiệu hóa",
    VOUCHER_DISABLED: "Voucher đã bị vô hiệu hóa",
    VOUCHER_CODE_DISABLED: "Mã voucher đã bị vô hiệu hóa",
    VOUCHER_CODE_MAX_USED: "Mã voucher đã hết lượt sử dụng",
    VOUCHER_EXPIRED: "Voucher đã hết hạn",
    VOUCHER_UNUSABLE: "Voucher không khả dụng",
    VOUCHER_CODE_AND_PHONE_NOT_MATCH: "Mã voucher không đúng với số điện thoại",
    VOUCHER_CODE_INVALID: "Mã voucher không hợp lệ",
    PRODUCT_STOP_TRADING: "Sản phẩm đã ngừng kinh doanh",
    ORDER_PRODUCT_NOT_FOUND: "Không tìm thấy sản phẩm đã đặt",
    ORDER_PRODUCT_NOT_MATCH_ORDER: "Sản phẩm đã đặt không khớp đơn hàng",
    ORDER_PRODUCT_CANCEL_REASON_REQUIRED: "Lí do hủy sản phẩm không được bỏ trống",
    INVALID_ORDER_STATUS: "Trạng thái đơn hàng không hợp lệ",
    SEAT_NOT_IN_SAME_STORE: "Chỗ ngồi không cùng cửa hàng",
    NOTIFICATION_NOT_IN_STORE: "Thông báo không thuộc cửa hàng này",
    STORE_NOTIFICATION_NOT_FOUND: "Không tìm thấy thông báo của cửa hàng",
    USER_PROFILE_NOT_FOUND: "Không tìm thấy thông tin người dùng",
    SALE_NOT_FOUND: "Không tìm thấy khuyến mãi",
    INVALID_SALE_TIME_CONDITION: "Thời gian khuyến mãi không hợp lệ",
    SALE_DISABLED: "Khuyến mãi đã bị vô hiệu hóa",
    SALE_NOT_STARTED: "Chưa tới thời gian bắt đầu của khuyến mãi",
    SALE_ENDED: "Khuyến mãi đã kết thúc",
    STORE_SALE_NOT_FOUND: "Không tìm thấy khuyến mãi của cửa hàng",
    STORE_SALE_DISABLED: "Khuyến mãi của cửa hàng đã bị vô hiệu hóa",
    FILE_NOT_FOUND: "Không tìm thấy file",
    TOPIC_SUBSCRIPTION_DENIED: "Không có quyền đăng ký chủ đề"
  },
  optionArray: [
    {value: "APP_ERROR", label: "Lỗi máy chủ"},
    {value: "BAD_REQUEST", label: "Yêu cầu không hợp lệ"},
    {value: "FORBIDDEN", label: "Yêu cầu bị chặn"},
    {value: "NOT_FOUND", label: "Không tìm thấy"},
    {value: "UNAUTHORIZED", label: "Chưa được xác thực"},
    {value: "AREA_NOT_FOUND", label: "Không tìm thấy khu vực"},
    {value: "EMAIL_EXIST", label: "Email đã tồn tại"},
    {value: "INVALID_OPERATION", label: "Thao tác không hợp lệ"},
    {value: "LOGIN_EXIST", label: "Tên đăng nhập đã tồn tại"},
    {value: "ORDER_FEEDBACK_EXIST", label: "Phản hồi đã tồn tại"},
    {value: "ORDER_FEEDBACK_NOT_FOUND", label: "Không tìm thấy phản hồi cho đơn hàng"},
    {value: "ORDER_NOT_FOUND", label: "Không tìm thấy đơn hàng"},
    {value: "PHONE_EXIST", label: "Số điện thoại đã tồn tại"},
    {value: "SEAT_NOT_FOUND", label: "Không tìm thấy chỗ ngồi"},
    {value: "STORE_NOT_FOUND", label: "Không tìm thấy cửa hàng"},
    {value: "STORE_USER_EXIST", label: "Nhân viên đã tồn tại"},
    {value: "USER_NOT_FOUND", label: "Không tìm thấy người dùng"},
    {value: "USER_NOT_ACTIVATED", label: "Người dùng chưa được kích hoạt"},
    {value: "STORE_USER_NOT_FOUND", label: "Không tìm thấy nhân viên"},
    {value: "RESET_KEY_NOT_FOUND_OR_EXPIRED", label: "Mã khôi phục đã hết hạn hoặc không tìm thấy"},
    {value: "CATEGORY_NAME_EXIST", label: "Tên danh mục đã tồn tại"},
    {value: "CATEGORY_NOT_FOUND", label: "Không tìm thấy danh mục"},
    {value: "PRODUCT_CODE_EXIST", label: "Mã sản phẩm đã tồn tại"},
    {value: "PRODUCT_NOT_FOUND", label: "Không tìm thấy sản phẩm"},
    {value: "CATEGORY_NAME_ENG_EXIST", label: "Tên danh mục tiếng anh đã tồn tại"},
    {value: "STORE_PRODUCT_NOT_FOUND", label: "Không tìm thấy sản phẩm của cửa hàng"},
    {value: "VOUCHER_NOT_FOUND", label: "Không tìm thấy voucher"},
    {value: "VOUCHER_CODE_NOT_FOUND", label: "Không tìm thấy mã voucher"},
    {value: "INCORRECT_CURRENT_PASSWORD", label: "Mật khẩu hiện tại không đúng"},
    {value: "AREA_DISABLED", label: "Khu vực đã bị khóa"},
    {value: "SEAT_LOCKED", label: "Chỗ ngồi đã bị khóa"},
    {value: "SEAT_NON_EMPTY", label: "Chỗ ngồi đã được sử dụng"},
    {value: "STORE_PAY_REQUEST_EXIST", label: "Yêu cầu thanh toán đã tồn tại"},
    {value: "PAY_AMOUNT_NOT_ENOUGH", label: "Tiền thanh toán không đủ"},
    {value: "ORDER_AND_SEAT_NOT_MATCH", label: "Đơn hàng không khớp vị trí"},
    {value: "LIST_ORDER_PRODUCT_EMPTY", label: "Danh sách sản phẩm trống"},
    {value: "ORDER_PURCHASED", label: "Đơn đã được thanh toán"},
    {value: "ORDER_CANCELLED", label: "Đơn đã bị hủy"},
    {value: "STORE_PRODUCT_STOP_TRADING", label: "Sản phẩm đã ngừng kinh doanh"},
    {value: "STORE_PRODUCT_UNAVAILABLE", label: "Sản phẩm đã hết hàng"},
    {value: "USER_NOT_IN_STORE", label: "Người dùng không thuộc cửa hàng"},
    {value: "STORE_CLOSED_OR_DEACTIVATED", label: "Cửa hàng đã đóng cửa hoặc bị vô hiệu hóa"},
    {value: "VOUCHER_DISABLED", label: "Voucher đã bị vô hiệu hóa"},
    {value: "VOUCHER_CODE_DISABLED", label: "Mã voucher đã bị vô hiệu hóa"},
    {value: "VOUCHER_CODE_MAX_USED", label: "Mã voucher đã hết lượt sử dụng"},
    {value: "VOUCHER_EXPIRED", label: "Voucher đã hết hạn"},
    {value: "VOUCHER_UNUSABLE", label: "Voucher không khả dụng"},
    {value: "VOUCHER_CODE_AND_PHONE_NOT_MATCH", label: "Mã voucher không đúng với số điện thoại"},
    {value: "VOUCHER_CODE_INVALID", label: "Mã voucher không hợp lệ"},
    {value: "PRODUCT_STOP_TRADING", label: "Sản phẩm đã ngừng kinh doanh"},
    {value: "ORDER_PRODUCT_NOT_FOUND", label: "Không tìm thấy sản phẩm đã đặt"},
    {value: "ORDER_PRODUCT_NOT_MATCH_ORDER", label: "Sản phẩm đã đặt không khớp đơn hàng"},
    {value: "ORDER_PRODUCT_CANCEL_REASON_REQUIRED", label: "Lí do hủy sản phẩm không được bỏ trống"},
    {value: "INVALID_ORDER_STATUS", label: "Trạng thái đơn hàng không hợp lệ"},
    {value: "SEAT_NOT_IN_SAME_STORE", label: "Chỗ ngồi không cùng cửa hàng"},
    {value: "NOTIFICATION_NOT_IN_STORE", label: "Thông báo không thuộc cửa hàng này"},
    {value: "STORE_NOTIFICATION_NOT_FOUND", label: "Không tìm thấy thông báo của cửa hàng"},
    {value: "USER_PROFILE_NOT_FOUND", label: "Không tìm thấy thông tin người dùng"},
    {value: "SALE_NOT_FOUND", label: "Không tìm thấy khuyến mãi"},
    {value: "INVALID_SALE_TIME_CONDITION", label: "Thời gian khuyến mãi không hợp lệ"},
    {value: "SALE_DISABLED", label: "Khuyến mãi đã bị vô hiệu hóa"},
    {value: "SALE_NOT_STARTED", label: "Chưa tới thời gian bắt đầu của khuyến mãi"},
    {value: "SALE_ENDED", label: "Khuyến mãi đã kết thúc"},
    {value: "STORE_SALE_NOT_FOUND", label: "Không tìm thấy khuyến mãi của cửa hàng"},
    {value: "STORE_SALE_DISABLED", label: "Khuyến mãi của cửa hàng đã bị vô hiệu hóa"},
    {value: "FILE_NOT_FOUND", label: "Không tìm thấy file"},
    {value: "TOPIC_SUBSCRIPTION_DENIED", label: "Không có quyền đăng ký chủ đề"}
  ],
};
export default ErrorCode;
