const OrderTimelineStatus = {
  valueArray: [
    'CREATED',
    'RECEIVED',
    'PURCHASED',
    'CANCELLED',
    'UPDATE_ORDER',
    'CHANGE_SEAT',
    'UPDATE_PHONE',
    'AUTO_APPLY_SALE',
    'APPLY_SALE',
    'CANCEL_SALE',
    'APPLY_VOUCHER',
    'CANCEL_VOUCHER'],
  labelArray: [
    'Tạo đơn',
    'Tiếp nhận',
    'Thanh toán',
    'Hủy đơn',
    'Gọi món',
    'Đổi chỗ',
    'Cập nhật SĐT',
    'Tự động áp dụng khuyến mãi',
    'Áp dụng khuyến mãi',
    'Hủy khuyến mãi',
    'Áp dụng mã giảm giá',
    'Hủy mã giảm giá'],
  value: {
    CREATED: 'CREATED',
    RECEIVED: 'RECEIVED',
    PURCHASED: 'PURCHASED',
    CANCELLED: 'CANCELLED',
    UPDATE_ORDER: 'UPDATE_ORDER',
    CHANGE_SEAT: 'CHANGE_SEAT',
    UPDATE_PHONE: 'UPDATE_PHONE',
    AUTO_APPLY_SALE: 'AUTO_APPLY_SALE',
    APPLY_SALE: 'APPLY_SALE',
    CANCEL_SALE: 'CANCEL_SALE',
    APPLY_VOUCHER: 'APPLY_VOUCHER',
    CANCEL_VOUCHER: 'CANCEL_VOUCHER',
  },
  label: {
    CREATED: 'Tạo đơn',
    RECEIVED: 'Tiếp nhận',
    PURCHASED: 'Thanh toán',
    CANCELLED: 'Hủy đơn',
    UPDATE_ORDER: 'Gọi món',
    CHANGE_SEAT: 'Đổi chỗ',
    UPDATE_PHONE: 'Cập nhật SĐT',
    AUTO_APPLY_SALE: 'Tự động áp dụng khuyến mãi',
    APPLY_SALE: 'Áp dụng khuyến mãi',
    CANCEL_SALE: 'Hủy khuyến mãi',
    APPLY_VOUCHER: 'Áp dụng mã giảm giá',
    CANCEL_VOUCHER: 'Hủy mã giảm giá',
  },
  optionArray: [
    {value: 'CREATED', label: 'Tạo đơn'},
    {value: 'RECEIVED', label: 'Tiếp nhận'},
    {value: 'PURCHASED', label: 'Thanh toán'},
    {value: 'CANCELLED', label: 'Hủy đơn'},
    {value: 'UPDATE_ORDER', label: 'Gọi món'},
    {value: 'CHANGE_SEAT', label: 'Đổi chỗ'},
    {value: 'UPDATE_PHONE', label: 'Cập nhật SĐT'},
    {value: 'AUTO_APPLY_SALE', label: 'Tự động áp dụng khuyến mãi'},
    {value: 'APPLY_SALE', label: 'Áp dụng khuyến mãi'},
    {value: 'CANCEL_SALE', label: 'Hủy khuyến mãi'},
    {value: 'APPLY_VOUCHER', label: 'Áp dụng mã giảm giá'},
    {value: 'CANCEL_VOUCHER', label: 'Hủy mã giảm giá'},
  ],
};
export default OrderTimelineStatus;
