const Roles = {
  ADMIN: "ROLE_ADMIN",
  MODERATOR: "ROLE_MODERATOR",
  PARTNER: "ROLE_PARTNER",
  CUSTOMER_CARE: "ROLE_CUSTOMER_CARE",
  USER: "ROLE_INTERNAL_USER",
  CUSTOMER: "ROLE_CUSTOMER"
};
export default Roles;
